### ISSUE TITLE
Please include license

### ISSUE THREAD

**Issue by oschwald** [evolvedm/geoip2#1]
As this is a copy of [geoip2](https://github.com/oschwald/geoip2-golang] and [maxminddb](https://github.com/oschwald/maxminddb-golang), could you please include the [LICENSE](https://github.com/oschwald/maxminddb-golang/blob/master/LICENSE)? Thanks!

**Comment by karimelm** [comment]
Hi Gregory,

 

Added, planned on doing, copied the files over instead of forking because I wanted to merge the 2 libs.

Thanks for creating this!

 

Karim

**Comment by oschwald** [comment]
Thanks!
